version: 0.2

env:
  parameter-store:
    ACCESS_KEY: "access-key-amplify-dev-test"
    SECRET_KEY: "secret-key-amplify-dev-test"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - npm install -g @aws-amplify/cli
      # - npm install -g pm2
      # - npm install -g wait-on
  build:
    commands:
      - echo Build started...
      - aws configure set aws_access_key_id $ACCESS_KEY
      - aws configure set aws_secret_access_key $SECRET_KEY
      - aws configure set default.region $AWS_REGION
      - sh ./amplifyPush.sh -e dev
      - npm run build
      - npm run test:ci
      # - pm2 start npm -- start
      # - wait-on http://localhost:3000
      # - node_modules/.bin/cypress run
      - echo Build finished on `date`

#Testing feature
reports:
  UnitTestReport: # CodeBuild will create a report group called "TestReport".
    files: #Store all of the files
      - "junit.xml"
    base-directory: "./"
  # TestReport: # CodeBuild will create a report group called "TestReport".
  #   files: #Store all of the files
  #     - "**/*"
  #   base-directory: "results"
artifacts:
  files:
    - "**/*"
  base-directory: "build"
