version: 0.2

env:
  parameter-store:
    ACCESS_KEY: "access-key-amplify-dev-test"
    SECRET_KEY: "secret-key-amplify-dev-test"
    ENV: "amplifyEnvDev"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - npm install -g @aws-amplify/cli
      - npm install -g typescript
      - npm install -g @angular/cli
      - npm install -g @angular-devkit/build-angular
  build:
    commands:
      - echo Build started...
      - aws configure set aws_access_key_id $ACCESS_KEY
      - aws configure set aws_secret_access_key $SECRET_KEY
      - aws configure set default.region $AWS_REGION
      - sh ./amplifyPush.sh -e $ENV
      - ng build
      - echo Build finished on `date`
  post_build:
    commands:
      - aws s3 sync ./dist $S3_BUCKET
artifacts:
  files:
    - "**/*"
  base-directory: "dist"
